services:
  - type: web
    name: matrixvis-web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
  - type: web
    name: martrixvis-lite
    env: docker
    plan: free
    autoDeploy: true
    rootDir: streamlit_variants/lite
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
  - type: web
    name: martrixvis
    env: docker
    plan: free
    autoDeploy: true
    rootDir: streamlit_variants/replacement
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
  - type: web
    name: martrixvis-zh
    env: docker
    plan: free
    autoDeploy: true
    rootDir: streamlit_variants/repo_skin_zh
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
  - type: web
    name: martrixvis-home
    env: docker
    plan: free
    autoDeploy: true
    rootDir: streamlit_variants/repo_skin_node_home
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
